# Generated by Django 3.1.7 on 2021-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_type', '0001_initial'),
        ('act', '0002_auto_20210314_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='act_types',
            field=models.ManyToManyField(blank=True, related_name='acts', to='act_type.ActType'),
        ),
    ]
