# Generated by Django 3.1.7 on 2021-03-15 13:21

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_act_timelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='end_datetime_local_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='UTC'),
        ),
        migrations.AlterField(
            model_name='act',
            name='start_datetime_local_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='UTC'),
        ),
    ]
