# Generated by Django 3.1.7 on 2021-03-18 19:35

import uuid

import ckeditor.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive_item', '0004_auto_20210318_2035'),
        ('annotation', '0008_auto_20210313_1454'),
        ('project', '0003_auto_20210315_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', ckeditor.fields.RichTextField(blank=True, default='', max_length=65535)),
                ('importance', models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')], default=0)),
                ('image_source', models.CharField(blank=True, max_length=512)),
                ('image_description', ckeditor.fields.RichTextField(blank=True, max_length=65535)),
                ('annotations', models.ManyToManyField(blank=True, related_name='annotations', to='annotation.Annotation')),
                ('archvie_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='archive_item.archiveitem')),
                ('projects', models.ManyToManyField(blank=True, related_name='pictures', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
