# Generated by Django 3.1.7 on 2021-03-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='archvie_item',
            new_name='archive_item',
        ),
    ]
