# Generated by Django 3.1.7 on 2021-03-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20210311_0037'),
        ('annotation', '0008_auto_20210313_1454'),
        ('artifact', '0002_auto_20210313_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='annotation.Annotation'),
        ),
    ]
