# Generated by Django 3.1.7 on 2021-03-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0003_auto_20210315_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='name_alt',
            field=models.CharField(blank=True, max_length=1025),
        ),
    ]
