# Generated by Django 3.1.7 on 2021-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
        ('artifact', '0004_artifact_name_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='picture.Picture'),
        ),
    ]
