# Generated by Django 3.1.7 on 2021-03-25 12:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0005_artifact_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='create_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='create_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='create_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='creator_raw',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000),
        ),
    ]
