# Generated by Django 3.1.7 on 2021-03-08 16:42

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0001_initial'),
        ('passage', '0004_auto_20210307_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField(max_length=65535)),
                ('original', models.BooleanField(default=False)),
                ('annotaions', models.ManyToManyField(related_name='comments', to='annotation.Annotation')),
                ('passages', models.ManyToManyField(related_name='comments', to='passage.Passage')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
