# Generated by Django 3.1.7 on 2021-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='original',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='passages',
            field=models.ManyToManyField(blank=True, related_name='comments', to='passage.Passage'),
        ),
    ]
