# Generated by Django 3.1.7 on 2021-03-09 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PAGE', 'Page')], default='PAGE', max_length=200)),
                ('identifier', models.CharField(default='1', max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='document.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
