# Generated by Django 3.1.7 on 2021-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210318_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
