# Generated by Django 3.1.7 on 2021-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='role',
            field=models.CharField(choices=[('ACTANT', 'Actant'), ('RECIPIENT', 'Recipient')], default='ACTANT', max_length=255),
        ),
    ]
