# Generated by Django 3.1.7 on 2021-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
        migrations.AddField(
            model_name='place',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
