# Generated by Django 3.1.7 on 2021-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acttype',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='acttype',
            name='name_cn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='acttype',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
