# Generated by Django 3.1.7 on 2021-03-09 02:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive_item', '0001_initial'),
        ('keyterm', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DOCUMENT', 'Document'), ('WEB', 'Web')], default='DOCUMENT', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=65535, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=65535, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('archive_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='archive_item.archiveitem')),
                ('keyterms', models.ManyToManyField(blank=True, related_name='documents', to='keyterm.Keyterm')),
                ('projects', models.ManyToManyField(blank=True, related_name='documents', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
