# Generated by Django 3.1.7 on 2021-03-07 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=65535),
        ),
    ]
