# Generated by Django 3.1.7 on 2021-03-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20210309_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='text',
        ),
    ]
