# Generated by Django 3.1.7 on 2021-03-08 16:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0003_auto_20210308_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marked_text', ckeditor.fields.RichTextField(blank=True, max_length=65535)),
                ('modified_date', models.DateTimeField(blank=True)),
                ('annotation_type', models.CharField(blank=True, max_length=255)),
                ('page_index', models.IntegerField(blank=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='document.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
