# Generated by Django 3.1.7 on 2021-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
