# Generated by Django 3.1.7 on 2021-03-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210308_1742'),
        ('annotation', '0002_annotation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='document.document'),
        ),
    ]
