# Generated by Django 3.1.7 on 2021-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20210309_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')], default=0),
        ),
    ]
