# Generated by Django 3.1.7 on 2021-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_passage_language'),
        ('annotation', '0003_auto_20210309_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='passages',
            field=models.ManyToManyField(blank=True, related_name='annotations', to='passage.Passage'),
        ),
    ]
