# Generated by Django 3.1.7 on 2021-03-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_passage_language'),
        ('annotation', '0004_annotation_passages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='passages',
        ),
        migrations.AddField(
            model_name='annotation',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='passage.passage'),
        ),
    ]
