# Generated by Django 3.1.7 on 2021-03-08 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_annotaions'),
        ('annotation', '0005_auto_20210308_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='comments',
            field=models.ManyToManyField(related_name='annotations', to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
