# Generated by Django 3.1.7 on 2021-03-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20210312_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='keyterms_raw',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
