# Generated by Django 3.1.7 on 2021-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_type', '0001_initial'),
        ('annotation', '0006_annotation_keyterms_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_type',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='annotation_type.annotationtype'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='time_raw',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
