# Generated by Django 3.1.7 on 2021-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_type', '0001_initial'),
        ('annotation', '0007_auto_20210313_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_types',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_types',
            field=models.ManyToManyField(blank=True, related_name='annotations', to='annotation_type.AnnotationType'),
        ),
    ]
