# Generated by Django 3.1.7 on 2021-03-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_auto_20210318_2352'),
        ('video', '0005_auto_20210318_2352'),
        ('annotation', '0008_auto_20210313_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='picture.picture'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='video.video'),
        ),
    ]
