# Generated by Django 3.1.7 on 2021-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutiontype',
            old_name='nameCn',
            new_name='name_cn',
        ),
    ]
