# Generated by Django 3.1.7 on 2021-03-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_auto_20210318_2352'),
        ('point', '0002_point_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='annotations',
            field=models.ManyToManyField(blank=True, to='annotation.Annotation'),
        ),
        migrations.AddField(
            model_name='point',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_point_children_+', to='point.Point'),
        ),
        migrations.AddField(
            model_name='point',
            name='gist',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='point',
            name='manuscript',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='point',
            name='target',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
