# Generated by Django 3.1.7 on 2021-03-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_auto_20210321_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
