# Generated by Django 3.1.7 on 2021-03-21 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_auto_20210318_2352'),
        ('point', '0004_point_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='points', to='annotation.Annotation'),
        ),
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
