# Generated by Django 3.1.7 on 2021-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_auto_20210321_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='point.Point'),
        ),
    ]
