# Generated by Django 3.1.7 on 2021-03-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0007_auto_20210321_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='point.point'),
        ),
    ]
