# Generated by Django 3.1.7 on 2021-03-25 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210313_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=65535),
        ),
    ]
