# Generated by Django 3.1.7 on 2021-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210315_1440'),
        ('debatable', '0002_auto_20210315_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatable',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='debatables', to='project.Project'),
        ),
    ]
