# Generated by Django 3.1.7 on 2021-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('debatable', '0003_debatable_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatable',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='debatables', to='topic.Topic'),
        ),
    ]
