# Generated by Django 3.1.7 on 2021-03-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20210311_0037'),
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='location',
        ),
        migrations.AddField(
            model_name='passage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='document.document'),
        ),
    ]
