# Generated by Django 3.1.7 on 2021-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_auto_20210311_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='page_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
