# Generated by Django 3.1.7 on 2021-03-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_auto_20210307_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='events',
        ),
    ]
