# Generated by Django 3.1.7 on 2021-03-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('passage', '0003_remove_passage_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='source_documents',
        ),
        migrations.AddField(
            model_name='passage',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passage', to='location.location'),
        ),
    ]
