# Generated by Django 3.1.7 on 2021-03-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_passage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
