# Generated by Django 3.1.7 on 2021-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_remove_picture_annotations'),
        ('passage', '0005_passage_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='picture.Picture'),
        ),
    ]
