# Generated by Django 3.1.7 on 2021-03-09 02:05

import uuid

import ckeditor.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keyterm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gist', models.CharField(max_length=225)),
                ('notes', ckeditor.fields.RichTextField(blank=True, max_length=65535)),
                ('keyterms', models.ManyToManyField(blank=True, related_name='ideas', to='keyterm.Keyterm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
