# Generated by Django 3.1.7 on 2021-03-09 02:05

import uuid

import ckeditor.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FILE', 'File'), ('DOCUMENT', 'Document')], default='DOCUMENT', max_length=200)),
                ('key', models.CharField(blank=True, max_length=2000)),
                ('key_type', models.CharField(choices=[('CITE_KEY', 'Cite Key')], default='CITE_KEY', max_length=200)),
                ('file_path', models.CharField(blank=True, max_length=3000)),
                ('title', models.CharField(blank=True, max_length=2000)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2000)),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_items', to='archive.archive')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
