# Generated by Django 3.1.7 on 2021-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='file_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
