# Generated by Django 3.1.7 on 2021-03-18 19:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_item', '0003_auto_20210309_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiveitem',
            old_name='created_date',
            new_name='file_created_date',
        ),
        migrations.RenameField(
            model_name='archiveitem',
            old_name='modified_date',
            new_name='file_modified_date',
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='image_source_url',
            field=models.CharField(blank=True, max_length=2046),
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, max_length=65535),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='key_type',
            field=models.CharField(choices=[('CITE_KEY', 'Cite Key'), ('URL', 'Url')], default='CITE_KEY', max_length=200),
        ),
    ]
