# Generated by Django 3.1.7 on 2021-03-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_item', '0004_auto_20210318_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='type',
            field=models.CharField(choices=[('FILE', 'File'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image')], default='DOCUMENT', max_length=200),
        ),
    ]
