# Generated by Django 3.1.7 on 2021-03-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_item', '0006_archiveitem_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveitem',
            name='image_source_url',
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
