# Generated by Django 3.1.7 on 2021-03-21 02:23

from django.db import migrations, models
import human_digita.archive_item.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_item', '0007_auto_20210318_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='file',
            field=models.FileField(blank=True, upload_to=human_digita.archive_item.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=human_digita.archive_item.models.get_file_name),
        ),
    ]
