# Generated by Django 3.1.7 on 2021-03-07 18:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('first_name_cn', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('last_name_cn', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True)),
                ('death_date', models.DateField(blank=True)),
                ('bio_passages', models.ManyToManyField(blank=True, to='passage.Passage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
