# Generated by Django 3.1.7 on 2021-03-13 19:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_auto_20210313_1454'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio_passages',
        ),
        migrations.AddField(
            model_name='person',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='people', to='annotation.Annotation'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=ckeditor.fields.RichTextField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name_cn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name_cn',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
