# Generated by Django 3.1.7 on 2021-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('actor', '0002_auto_20210307_1928'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='recepient',
        ),
        migrations.AlterField(
            model_name='action',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='actions', to='place.Place'),
        ),
        migrations.AlterField(
            model_name='action',
            name='second_recipients',
            field=models.ManyToManyField(blank=True, related_name='as_second_recipients', to='actor.Actor'),
        ),
    ]
