# Generated by Django 3.1.7 on 2021-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='raw_sentence',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='action',
            name='start_day_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='start_hour_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='start_month_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='start_year_local',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
