# Generated by Django 3.1.7 on 2021-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20210307_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='sentence',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
