# Generated by Django 3.1.7 on 2021-03-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20210312_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='types',
        ),
    ]
