# Generated by Django 3.1.7 on 2021-03-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_remove_act_types'),
        ('action_type', '0002_auto_20210312_2100'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='action',
            field=models.ManyToManyField(related_name='acts', to='action_type.Action'),
        ),
        migrations.AlterField(
            model_name='act',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='acts', to='place.Place'),
        ),
    ]
