# Generated by Django 3.1.7 on 2021-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_type', '0002_auto_20210312_2100'),
        ('actor', '0001_initial'),
        ('action', '0005_auto_20210312_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='actants',
            field=models.ManyToManyField(blank=True, related_name='as_actants', to='actor.Actor'),
        ),
        migrations.AlterField(
            model_name='act',
            name='action',
            field=models.ManyToManyField(blank=True, related_name='acts', to='action_type.Action'),
        ),
        migrations.AlterField(
            model_name='act',
            name='first_recipients',
            field=models.ManyToManyField(blank=True, related_name='as_first_recipients', to='actor.Actor'),
        ),
    ]
