# Generated by Django 3.1.7 on 2021-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20210312_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='sentence',
            field=models.CharField(default='', max_length=512),
        ),
    ]
