# Generated by Django 3.1.7 on 2021-03-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_auto_20210312_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='raw_sentence',
        ),
        migrations.AddField(
            model_name='act',
            name='keyterms_raw',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='act',
            name='sentence_raw',
            field=models.CharField(default='', max_length=2046),
        ),
        migrations.AlterField(
            model_name='act',
            name='sentence',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
